-- algorithms のデータを挿入
INSERT INTO algorithms (id, name) VALUES
    ('1', 'Implementation'),
    ('2', 'Math'),
    ('3', 'Greedy'),
    ('4', 'DP'),
    ('5', 'Data Structures'),
    ('6', 'Brute Force'),
    ('7', 'Constructive Algorithms'),
    ('8', 'Graphs'),
    ('9', 'Sortings'),
    ('10', 'Binary Search'),
    ('11', 'DFS and Similar'),
    ('12', 'Trees'),
    ('13', 'Strings'),
    ('14', 'Number Theory'),
    ('15', 'Combinatorics'),
    ('16', 'Geometry'),
    ('17', 'Bitmasks'),
    ('18', 'Two Pointers'),
    ('19', 'DSU'),
    ('20', 'Shortest Paths'),
    ('21', 'Probabilities'),
    ('22', 'Divide and Conquer'),
    ('23', 'Hashing'),
    ('24', 'Games'),
    ('25', 'Flows'),
    ('26', 'Interactive'),
    ('27', 'Matrices'),
    ('28', 'FFT'),
    ('29', 'Ternary Search'),
    ('30', 'Expression Parsing'),
    ('31', 'Meet-in-the-Middle'),
    ('32', '2-SAT'),
    ('33', 'Chinese Remainder Theorem'),
    ('34', 'Schedules'),
    ('35', 'Special'),
    ('36', 'Other'),
    ('37', 'Technique'),
    ('38', 'Query');

-- technique_tags のデータを挿入
INSERT INTO technical_tags (id, en_name, ja_name, algorithm_id) VALUES
    ('1', 'Implementation', '実装', '1'),
    ('2', 'Math', '数学', '2'),
    ('3', 'Greedy', '貪欲法', '3'),
    ('4', 'DP', '動的計画法', '4'),
    ('5', 'Data Structures', 'データ構造', '5'),
    ('6', 'Brute Force', '全探索', '6'),
    ('7', 'Constructive Algorithms', '構築', '7'),
    ('8', 'Graphs', 'グラフ', '8'),
    ('9', 'Sortings', 'ソート', '9'),
    ('10', 'Binary Search', '二分探索', '10'),
    ('11', 'DFS and Similar', 'DFS', '11'),
    ('12', 'Trees', '木', '12'),
    ('13', 'Strings', '文字列', '13'),
    ('14', 'Number Theory', '数論', '14'),
    ('15', 'Combinatorics', '組合せ', '15'),
    ('16', 'Geometry', '幾何', '16'),
    ('17', 'Bitmasks', 'ビット演算', '17'),
    ('18', 'Two Pointers', '尺取り法', '18'),
    ('19', 'DSU', 'Union Find', '19'),
    ('20', 'Shortest Paths', '最短経路', '20'),
    ('21', 'Probabilities', '確率', '21'),
    ('22', 'Divide and Conquer', '分割統治', '22'),
    ('23', 'Hashing', 'ハッシュ', '23'),
    ('24', 'Games', 'ゲーム', '24'),
    ('25', 'Flows', 'フロー', '25'),
    ('26', 'Interactive', 'インタラクティブ', '26'),
    ('27', 'Matrices', '行列', '27'),
    ('28', 'FFT', '高速フーリエ変換', '28'),
    ('29', 'Ternary Search', '三分探索', '29'),
    ('30', 'Expression Parsing', '構文解析', '30'),
    ('31', 'Meet-in-the-Middle', 'Meet-in-the-Middle', '31'),
    ('32', '2-SAT', '2-SAT', '32'),
    ('33', 'Chinese Remainder Theorem', '中国剰余定理', '33'),
    ('34', 'Schedules', 'スケジューリング', '34'),
    ('35', 'Special', '特殊', '35'),
    ('36', 'Other', 'その他', '36'),
    ('37', 'Technique', 'テクニック', '37'),
    ('42', 'Query', 'クエリ', '38'),

    -- 命名されていないテクニック (drken Blog 参考)
    ('38', 'Operation', '操作', '1'),
    ('39', 'Interval', '区間', '5'),
    ('40', 'RePhrasing', '条件の言い換え', '37'),
    ('41', 'Yes or No', 'Yes or No', '36'),
    ('43', 'Parity', 'パリティ', '2'),
    ('44', 'Two Dimensional Grid', '2次元グリッド', '8'),
    ('45', 'Preprocessing', '前処理', '1'),
    ('46', 'Fixing a Quantity', 'ある量を固定', '37'),
    ('47', 'Cumulative Sum', '累積和', '5'),
    ('49', 'Binomial Coefficient', '二項係数', '14'),
    ('51', 'Corner Case', 'コーナーケース', '1'),
    ('52', 'Permutation', '順列', '15'),
    ('53', 'Update Difference', '差分更新', '38'),
    ('54', 'Floating Point', '浮動小数点', '2'),
    ('55', 'Speed Up DP', 'DPの高速化', '4'),
    ('56', 'N Points On A Two Dimensional Plane', '2次元平面上のN点','8'),
    ('57', 'Segment Tree', 'セグメント木', '5'),
    ('58', 'Number Seqence', '数列', '2');